Fix a few issues with functions on superposition
cscherrer/MeasureBase.jl pull request #46
Opened 2022-05-03 12:34 UTC by theogf

This fixes a few issues where functions where specialized for only 2-tuples of measure.

2022-05-03 13:58 UTC, cscherrer reviewed
Thanks @theogf , I've added a few comments/questions

2022-05-03 13:58 UTC, cscherrer commented on src/combinators/superpose.jl
> +end
What problem do you see with
```julia
density_def(μ, x) = exp(logdensity_def(μ, x))
```
?

2022-05-03 13:58 UTC, cscherrer commented on src/combinators/superpose.jl
> +        return logdensity_def(μ, x) - logdensity_def(ν, x)
Is this just a formatting change? That's fine, just want to be sure.

We should also drop the `::Any`, since it's not needed

2022-05-03 13:58 UTC, cscherrer commented on src/combinators/superpose.jl
> +) where {A,B}
Also just formatting?

2022-05-03 13:58 UTC, cscherrer commented on src/combinators/superpose.jl
> +basemeasure(μ::SuperpositionMeasure) = superpose(map(basemeasure, μ.components))
This makes me wonder if we should go even farther in this direction. Should we be doing `...` at all for superpositions? If so, I think we're missing a method like
```julia
superpose(m1, m2, ms...) = ...
```
But maybe we should just be doing this within a Tuple?

2022-05-03 14:04 UTC, theogf commented on src/combinators/superpose.jl
> +        return logdensity_def(μ, x) - logdensity_def(ν, x)
Yeah sorry, I have this autoformatter on and it just changed things unwillingly :sweat_smile: 
If you are open to it, we could have one big PR to follow a formatting style and there is an action to automatically make formatting suggestions on PR.

2022-05-03 14:04 UTC, theogf commented on src/combinators/superpose.jl
> +) where {A,B}
Yes!

2022-05-03 14:10 UTC, theogf commented on src/combinators/superpose.jl
> +basemeasure(μ::SuperpositionMeasure) = superpose(map(basemeasure, μ.components))
What do you think of 
```julia
function superpose(μ, μs...)
    if all(==(μ), μs)
        return weightedmeasure(log(length(μs) + 1), μ)
    else
        return superpose((μ, μs...))
    end
end
```

2022-05-03 14:25 UTC, cscherrer commented on src/combinators/superpose.jl
> +end
But it can take a `Tuple{A,B}`. I think we're talking past each other - do you have an example that currently fails?

2022-05-03 14:39 UTC, cscherrer commented on src/combinators/superpose.jl
> +basemeasure(μ::SuperpositionMeasure) = superpose(map(basemeasure, μ.components))
By itself I like it, but we need to think through the context and the dispatch patterns that lead us to this.

Users can build a `SuperpositionMeasure` in a few ways. We need `a + b` and `sum((a,b))` to result in the same thing. I think we should have one method to handle both cases. Whether that's a method on Tuples or a `...` method mostly comes down to performance and which is more natural to code.

There's a fair amount more to do for general superpositions. In the end we need a data structure that encodes how the base measures are related, storing everything in a tree structure. That will make it easy to compute things efficiently, since it will let us share log-density computations. It will also make it easier to fold more measures into an existing superposition.

We'll also need to build the `logmass` API we've talked about before. I'll turn this comment into a new issue, so we can discuss there.

2022-05-03 14:43 UTC, theogf commented on src/combinators/superpose.jl
> +basemeasure(μ::SuperpositionMeasure) = superpose(map(basemeasure, μ.components))
> We need a + b and sum((a,b)) to result in the same thing. I think we should have one method to handle both cases.

I think the only thing to handle is the `a::SuperpositionMeasure + b::Measure` dispatch (two versions one for tuple and one for vectors).

2022-05-03 14:55 UTC, cscherrer commented on src/combinators/superpose.jl
> +basemeasure(μ::SuperpositionMeasure) = superpose(map(basemeasure, μ.components))
Ahh ok, so as a start, something like
```julia
superpose(a::AbstractMeasure, b::AbstractMeasure, ms...) = superpose(superpose(a, b), ms...)
superpose(a::SuperpositionMeasure, b::AbstractMeasure) = ...
superpose(a::AbstractMeasure) = a
```

2022-05-03 15:10 UTC, theogf commented on src/combinators/superpose.jl
> +        return logdensity_def(μ, x) - logdensity_def(ν, x)
I think this is configurable in a Style file

2022-05-03 15:10 UTC, theogf commented on src/combinators/superpose.jl
> +end
Yeah sure running `logdensityof(SuperpositionMeasure([Dirac(0), Dirac(2.0)]), 2.0)`

2022-05-08 14:05 UTC, cscherrer commented
I want to summarize something here that was confusing me a little...

We typically work in terms of `logdensity_def`, which is why we have methods
```julia
density_def(μ, ν::AbstractMeasure, x) = exp(logdensity_def(μ, ν, x))
density_def(μ, x) = exp(logdensity_def(μ, x))
```
But superpositions are more naturally expressed in "linear space", which is why I had added
```julia
@inline logdensity_def(s::SuperpositionMeasure, x) = log(density_def(s, x))
```

But as @theogf points out, this sets up a mutual recursion, so now the default case will blow the stack. So in this case, we're really depending on `density_def` being defined. To make this safer and more user-friendly, we should have a default method that throws an informative error, since this is more useful than a stack overflow. This leads us to
```julia
function density_def(s::SuperpositionMeasure, x)
    error("Not implemented")
end
```

2022-05-08 14:14 UTC, cscherrer requested changes

2022-05-08 14:14 UTC, cscherrer commented on src/combinators/superpose.jl
> +    error("Not implemented")
```suggestion
    T = typeof(s)
    msg = """
    Not implemented: There is no method
    density_def(::$T, x)
    """
    error(msg)
```

2022-05-08 14:14 UTC, cscherrer commented on src/combinators/smart-constructors.jl
>  kleisli(k::ParameterizedKleisli) = k
```suggestion
kleisli(k::ParameterizedKleisli) = k

```

2022-05-08 14:14 UTC, cscherrer commented on test/combinators/superpose.jl
> +end
```suggestion
end

```

2022-05-09 17:21 UTC, merged