Dev
cscherrer/MeasureBase.jl pull request #88
Opened 2022-09-12 01:57 UTC by cscherrer

2022-09-12 02:58 UTC, cscherrer commented
There's currently an error in tests. This correctly throws an error:
```julia
julia> transport_to(StdNormal(), StdUniform())([0.3, 0.4])
ERROR: ArgumentError: Invalid variate type for measure
Stacktrace:
 [1] checked_arg
   @ ~/git/MeasureBase.jl/src/primitives/lebesgue.jl:49 [inlined]
 [2] _default_checked_arg
   @ ~/git/MeasureBase.jl/src/getdof.jl:75 [inlined]
 [3] checked_arg
   @ ~/git/MeasureBase.jl/src/getdof.jl:79 [inlined]
 [4] (::MeasureBase.TransportFunction{StdNormal, StdUniform})(x::Vector{Float64})
   @ MeasureBase ~/git/MeasureBase.jl/src/transport.jl:211
 [5] top-level scope
   @ REPL[71]:1
```

But `StdNormal` does not yet behave properly:
```julia
julia> transport_to(StdNormal(), StdNormal())([0.3, 0.4])
MeasureBase.NoArgCheck{MeasureBase.LebesgueMeasure, Vector{Float64}}
```

2022-09-12 06:08 UTC, oschulz commented
I think we need

```julia
@inline MeasureBase.basemeasure(::StdNormal) = MeasureBase.WeightedMeasure(static(-0.5 * log2π), MeasureBase.Lebesgue())
```

So `Lebesgue()` instead of `LebesgueMeasure()`, otherwise `checked_arg` doesn't work. We also have `Lebesgue()` as the base measure for the other std measures.

2022-09-12 06:20 UTC, oschulz commented
Question, do we really need the intermediate `WeightedMeasure(static(-0.5 * log2π), ...)`? This might actually be faster, doing everything in one go

```
@inline logdensity_def(::StdNormal, x::U) where {U<:Real} = muladd(abs2(x), -U(1)/U(2), -log2π/U(2))
@inline basemeasure(::StdNormal) = Lebesgue()
```

since it can use hardware-based fused-multiply-add.

2022-09-12 13:32 UTC, cscherrer commented
> So `Lebesgue()` instead of `LebesgueMeasure()`, otherwise `checked_arg` doesn't work. We also have `Lebesgue()` as the base measure for the other std measures.

Previously, a lot of measures had `Lebesgue()` as their base measure, but `basemeasure(Lebesgue()) == LebesgueMeasure()`. This seems bad, because `Lebesgue()` and `LebesgueMeasure()` are functionally identical. The extra step was not immediately a problem, but it does make the `basemeasure_sequence` one step longer, for no real benefit. So if we build measures on measures on measures, my guess is that it would lead to compiler issues a little earlier.

The idea with separating `::Lebesgue` from `::LebesgueMeasure` in the first place was that the former can take a "domain" argument. Then `inbounds(Lebesgue(dom))` acts like `RestrictedMeasure(x -> in(x, dom), LebesgueMeasure())`. 

I think there are two possible solutions:
1. Use `LebesgueMeasure()` as the base measure wherever possible, and leave `Lebesgue` as a more flexible user-facing alternative. 
2. Drop `LebesgueMeasure` altogether, and use `Lebesgue{()}` in its place. It's still determined entirely by its type. 

> Question, do we really need the intermediate `WeightedMeasure(static(-0.5 * log2π), ...)`?

It would be convenient to change `MeasureTheory.Normal` to build on top of `StdNormal` instead of starting from scratch. The point of the `WeightedMeasure` is that if you have, say, a regression problem with `Normal` noise, the product of `Normal` measures will have a common base measure, which allows you to only compute it once. In MeasureTheory, this approach gets us just a little faster than Distributions, even for a single evaluation. I think the advantage might come from the `static`ness, but I'm not sure.

Anyway, we could sacrifice this convenience if `fma` gets us faster still. Maybe we should have a small collection of benchmarks to help guide us on things like this?

2022-09-12 13:34 UTC, cscherrer commented
Also, ...

> So `Lebesgue()` instead of `LebesgueMeasure()`, otherwise `checked_arg` doesn't work. We also have `Lebesgue()` as the base measure for the other std measures.

I added `@inline checked_arg(::LebesgueMeasure, x::Real) = x`. That got rid of lots of errors, but there's still the one I described above, which I don't yet understand.

2022-09-12 17:49 UTC, cscherrer commented
Right, this one has been kind of tricky. I think the invariant we need is that is `mu << LebesgueMeasure()` and `nu << LebesgueMeasure()`, then
```julia
logdensity_rel(mu, nu) == logdensity_rel(mu, LebesgueMeasure()) - logdensity_real(nu, LebesgueMeasure())
```

Say `mu` is a measure on the `x` axis, and `nu` is a measure on the `y` axis. Then the result we want is that they should be singular at the origin. Having LebesgueMeasure dominate both will cause problems. This makes me think maybe we should drop the idea that LebesgueMeasure is arbitrary, and only use it for measures on the real line.

@mschauer , do you have any thoughts on this?

2022-09-13 22:36 UTC, cscherrer commented
@oschulz I don't understand how `checked_arg` works, could you point me in the right direction? I'm getting
```julia
julia> using MeasureBase

julia> using Test

julia> using MeasureBase: getdof, check_dof, checked_arg

julia> μ0 = StdExponential()
StdExponential()

julia> x0 = rand(μ0)
0.8225907598317117

julia> μ2 = StdExponential()^(2, 3)
StdExponential() ^ (2, 3)

julia> x2 = rand(μ2)
2×3 Matrix{Float64}:
 1.59882   3.697    0.986999
 0.835304  0.80118  1.03364

julia>     @test_throws ArgumentError checked_arg(μ0, x2)
Test Failed at REPL[25]:1
  Expression: checked_arg(μ0, x2)
    Expected: ArgumentError
  No exception thrown
ERROR: There was an error during testing

julia> checked_arg(μ0, x2)
MeasureBase.NoArgCheck{MeasureBase.LebesgueMeasure, Matrix{Float64}}
```

2022-09-13 22:59 UTC, cscherrer commented on src/combinators/transformedmeasure.jl
> +
@oschulz what do you think of transporting pushforwards to the origin of the parent like this, instead of stopping at the parent?

2022-09-14 06:25 UTC, oschulz commented on src/combinators/transformedmeasure.jl
> +
That kind of forwarding should happen automatically, by the transport "resolver". I have some improvement on that in the works on the "typestable-transport" branch (will be back on this now).

2022-09-14 06:27 UTC, oschulz commented
> This makes me think maybe we should drop the idea that LebesgueMeasure is arbitrary, and only use it for measures on the real line.

To only one Lebesgue measure type? Yes, I think that would be less confusing. If we want only half of the real line or so, we can have a "restricted measure" wrapper or so.

2022-09-14 07:38 UTC, mschauer commented
I think the type system might not be expressive enough to have always the domain encoded into the Lebesgue measure: you'll have to do type arithmetic like the marginal of a SVector{2} lebesgue measure is a SVector{1} lebegue measure and that's something which in Julia at some point gets in the way of productivity.

2022-09-14 11:50 UTC, cscherrer commented on src/combinators/transformedmeasure.jl
> +
I see, so it sounds like you're recommending in general we only take a small step and let the resolver figure it out. Is that right?

2022-09-14 12:16 UTC, cscherrer commented
In the current setup:
1. We have a singleton type for the most common "Lebesgue measure on $\mathbb{R}$". This is currently called `LebesgueMeasure`
2. We have a convenience wrapper so users can construct "Lebesgue measure on ____". This is currently called `Lebesgue`. In some cases this acts like a `restrict` call, as in `Lebesgue(𝕀)`. In others in can be something completely different, like `Lebesgue(Simplex())`

We need (1) as a common base measure for any restricted Lebesgue measure, or as a root measure for any univariate continuous measure.

(2) is a convenience, but without it users would have to write things like `restrict(x -> 0<x<1, LebesgueMeasure)`. This gets even messier for things like "Lebesgue measure on a simplex".

I agree the naming is weird. Maybe we should change `LebesgueMeasure` to `LebesgueBase` to hint its intended use? Or we could talk about more fundamental refactoring if you have ideas.

2022-09-14 18:58 UTC, cscherrer commented on src/combinators/transformedmeasure.jl
> +pushfwd(f, finv, μ, volcorr::TransformVolCorr = WithVolCorr()) = PushforwardMeasure(f, finv, μ, volcorr)
Not working yet:
```julia
julia> μ = Lebesgue() ^ 2
Lebesgue(ℝ) ^ 2

julia> f(x) = [2x[1], x[2]]
f (generic function with 1 method)

julia> finv(y) = [y[1]/2, y[2]]
finv (generic function with 1 method)

julia> logdensityof(pushfwd(f, finv, μ), zeros(2))
ERROR: MethodError: no method matching iterate(::ChangesOfVariables.NoLogAbsDetJacobian{typeof(finv), Vector{Float64}})
Closest candidates are:
  iterate(::Union{LinRange, StepRangeLen}) at range.jl:872
  iterate(::Union{LinRange, StepRangeLen}, ::Integer) at range.jl:872
  iterate(::T) where T<:Union{Base.KeySet{<:Any, <:Dict}, Base.ValueIterator{<:Dict}} at dict.jl:712
  ...
Stacktrace:
 [1] indexed_iterate(I::ChangesOfVariables.NoLogAbsDetJacobian{typeof(finv), Vector{Float64}}, i::Int64)
   @ Base ./tuple.jl:91
 [2] logdensity_def
   @ ~/git/MeasureBase.jl/src/combinators/transformedmeasure.jl:62 [inlined]
 [3] unsafe_logdensityof
   @ ~/git/MeasureBase.jl/src/density.jl:139 [inlined]
 [4] logdensityof(μ::PushforwardMeasure{typeof(f), typeof(finv), PowerMeasure{Lebesgue{MeasureBase.RealNumbers}, Tuple{Base.OneTo{Int64}}}, MeasureBase.WithVolCorr}, x::Vector{Float64})
   @ MeasureBase ~/git/MeasureBase.jl/src/density.jl:123
 [5] top-level scope
   @ REPL[46]:1
```

2022-09-14 20:03 UTC, oschulz commented on src/combinators/transformedmeasure.jl
> +
Yes, exactly.

2022-09-14 20:04 UTC, oschulz commented on src/combinators/transformedmeasure.jl
> +
And it has a barrier against infinite recursion built in.

2022-09-15 16:37 UTC, cscherrer commented on src/combinators/transformedmeasure.jl
> +pushfwd(f, finv, μ, volcorr::TransformVolCorr = WithVolCorr()) = PushforwardMeasure(f, finv, μ, volcorr)
It works!!
```julia
julia> using MeasureBase, ForwardDiff, ChangesOfVariables, IrrationalConstants

julia> μ = Lebesgue(MeasureBase.BoundedReals(-halfπ, halfπ))
Lebesgue(MeasureBase.BoundedReals{Float64, Irrational{:halfπ}}(-1.5707963267948966, halfπ))

julia> function f(x)
           asin(x)
       end
f (generic function with 1 method)

julia> function finv(y)
           if -halfπ ≤ y ≤ halfπ
               return sin(y)
           else
               @error "finv is only defined on [-π/2, π/2]"
           end
       end
finv (generic function with 1 method)

julia> function withlogjac(f, x)
           dx = ForwardDiff.Dual{ForwardDiff.Tag{typeof(f)}}(x, 1.0)
           dy = f(dx)
           value = dy.value
           deriv = first(dy.partials)
           (value, log(abs(deriv)))   
       end
withlogjac (generic function with 1 method)

julia> function ChangesOfVariables.with_logabsdet_jacobian(::typeof(f), x)
           withlogjac(f, x)
       end

julia> function ChangesOfVariables.with_logabsdet_jacobian(::typeof(finv), x)
           withlogjac(finv, x)
       end

julia> # Both of these pass
       ChangesOfVariables.test_with_logabsdet_jacobian(f, 2 * rand() - 1, ForwardDiff.derivative)
Test Summary:                                                 | Pass  Total  Time
test_with_logabsdet_jacobian: f with input 0.9708087843236501 |    2      2  0.0s

julia> ChangesOfVariables.test_with_logabsdet_jacobian(finv, π * rand() - halfπ, ForwardDiff.derivative)
Test Summary:                                                     | Pass  Total  Time
test_with_logabsdet_jacobian: finv with input 0.43781065021456067 |    2      2  0.0s

julia> ν = pushfwd(f, finv, μ)
PushforwardMeasure(
    f,
    finv,
    Lebesgue(MeasureBase.BoundedReals{Float64, Irrational{:halfπ}}(-1.5707963267948966, halfπ)))

julia> logdensityof(ν, π/4)
-0.3465735902799726
```

2022-09-15 16:39 UTC, cscherrer commented
I got the `pushfwd(f, finv, μ)` for working, but I noticed some issues along the way:
https://github.com/cscherrer/MeasureBase.jl/issues/89

2022-09-16 06:15 UTC, mschauer commented on src/combinators/transformedmeasure.jl
> +pushfwd(f, finv, μ, volcorr::TransformVolCorr = WithVolCorr()) = PushforwardMeasure(f, finv, μ, volcorr)
🎉 juhu!

2022-09-16 07:37 UTC, oschulz commented
Can we *not* add `pushfwd(f, finv, μ)`? I think we can make JuliaMath/InverseFunctions.jl#18 happen.

2022-09-16 16:14 UTC, cscherrer commented
I agree it's better to solve the problem once in InverseFunctions than for every user to replicate the work. But for users of MeasureBase, `pushfwd(f, finv, μ)` still seems much better than `pushfwd(setinverse(f, finv), μ)`. We could have a single line to make this definition, and save everyone downstream some typing. Do you see problem with this approach?

2022-09-16 19:23 UTC, oschulz commented
> We could have a single line to make this definition, and save everyone downstream some typing.We could have a single line to make this definition, and save everyone downstream some typing.

Oh, you mean this would do

```
pushfwd(f, finv, μ) = pushfwd(setinverse(f, finv), μ)
```

Once we have that capability in InverseFunctions? Yes, that would be very user friendly, I like it.

2022-09-19 18:29 UTC, oschulz commented
Regarding `massof` - I think it would be more natural if it returns a `Real` (or static real) if the mass is known, and `UnknownFiniteMass` resp. `UnknownMass` otherwise.

2022-09-19 18:31 UTC, oschulz commented
`isnormalized` I would see as something that only operates on measures, not on return values of `massof`. It's also a tricky choice of function name, since we probably shouldn't export something that generic.

2022-09-19 18:36 UTC, oschulz commented
Regarding `normalize(m::AbstractMeasure) = normalize(m, massof(m))` - this may not be ideal, since the second argument of `LinearAlgebra.normalize` has very different semantics by default (indicating the type of norm, not the current norm value). Maybe that should be `normalize(m::AbstractMeasure) = renormalize(m, 1/massof(m))` or no?

2022-09-19 18:45 UTC, cscherrer commented
> Regarding `massof` - I think it would be more natural if it returns a `Real` (or static real) if the mass is known, and `UnknownFiniteMass` resp. `UnknownMass` otherwise.

We could take this a step further and use `missing` instead of `UnknownMass()`. But then it seems strange to only have `UnknownFiniteMass` as special.

> `isnormalized` I would see as something that only operates on measures, not on return values of `massof`.

I agree. What I have is just for dispatch, but there it should probably be `_isnormalized`.

> It's also a tricky choice of function name, since we probably shouldn't export something that generic.

I think my position on this is the same as my position on software patents. It would be better if no one did it. But they do, and if you don't you're only hurting yourself. 

MeasureBase is a pretty fundamental package. If someone else wants a name for a non-measure use we can talk about splitting out an interface package.

> Regarding `normalize(m::AbstractMeasure) = normalize(m, massof(m))` - this may not be ideal, since the second argument of `LinearAlgebra.normalize` has very different semantics by default (indicating the type of norm, not the current norm value). Maybe that should be `normalize(m::AbstractMeasure) = renormalize(m, 1/massof(m))` or no?

This is a good point, especially if we make `massof` sometimes return a float.

2022-09-19 19:15 UTC, oschulz commented
> We could take this a step further and use missing instead of UnknownMass(). But then it seems strange to only have UnknownFiniteMass as special.

Hm, yes. One advantage of `UnknownMass{MeasureType}()` would be that it helps more with debugging than missing, e.g. when code tries to do math with the result of `massof`, you'd get an error that includes the measure type (even if the value has been passed around already).

2022-09-19 19:19 UTC, oschulz commented
>> isnormalized ... we probably shouldn't export something that generic
> MeasureBase is a pretty fundamental package

True, but `normalize` is defined in `LinearAlgebra`, which is another level of fundamental. So if we export `isnormalized`, it would fall to us to also support it for arrays and so on, since no other package could do so without committing type piracy ...

2022-09-19 19:58 UTC, cscherrer commented
> True, but `normalize` is defined in `LinearAlgebra`, which is another level of fundamental. So if we export `isnormalized`, it would fall to us to also support it for arrays and so on, since no other package could do so without committing type piracy ...

I see, people would expect other methods just because of the name. Well, I think it's almost trivial to provide that in an extensible way. We just set
```julia
isnormalized(x, p::Real=2) = isone(norm(x, p))
```

Or we could just not export it, if you think it's a bad idea.

2022-09-19 21:33 UTC, cscherrer commented on src/mass-interface.jl
> +logmassof(m::AbstractMeasure) = log(massof(m))
```suggestion
```

Maybe we should wait on this? It will require a separate version of the above types and methods, which seems kind of heavy for relatively little benefit. Not sure yet about this.

2022-09-22 22:05 UTC, cscherrer commented
You can now do e.g.
```julia
julia> (MeasureBase.StdNormal())(2..4)
0.02271846070634609
```
@oschulz pointed out that while this works well for `<:AbstractMeasure`s, this is difficult to generalize. For example, DistributionMeasures helps `Distribution`s satisfy the measure interface, but we can't just make them callable. We'll need another option. For example, we could introduce a two-argument `massof` method.

2022-09-26 23:17 UTC, cscherrer commented on src/combinators/powerweighted.jl
> +massof(m::PowerWeightedMeasure) = massof(m.parent)^m.exponent
This is wrong

2022-09-29 01:56 UTC, cscherrer commented
I think this might be pretty close. We still need to update the transport definitions for weighted measures. I think it's important for mass to be invariant under transports; otherwise it's easy for things to get mixed up. With invariant mass we'll be able to use the transport API to get the measure of an interval, basically an extension of the usual `cdf` on unit-mass measures.

2022-09-29 08:38 UTC, oschulz commented
> I think it's important for mass to be invariant under transports

I agree.

2022-10-03 16:21 UTC, cscherrer commented
I think I see the problem. I changed it back here:
https://github.com/cscherrer/MeasureBase.jl/pull/88/commits/d0530c3bc2891243d21a052139aaeb9d99f381a8

But now there's nothing enforcing that transports should preserve mass, so we'll need to figure that out. @oschulz I think you had a suggestion for this?

2022-10-10 22:56 UTC, cscherrer commented on src/combinators/transformedmeasure.jl
> +getdof(μ::PushforwardMeasure) = getdof(transport_origin(μ))
```suggestion
```
Duplicate method

2022-10-15 19:34 UTC, oschulz requested changes

2022-10-15 19:34 UTC, oschulz commented on src/combinators/transformedmeasure.jl
> +    finv::I
Why not keep `inv_f`, as before?

2022-10-15 19:34 UTC, oschulz commented on src/combinators/transformedmeasure.jl
> +function transport_def(ν::PushforwardMeasure{F,I,M}, μ::M, x) where {F,I,M}
Do we need `transport_def` for `PushforwardMeasure`? It shouldn't be necessary since `PushforwardMeasure` should use the "origin path" for transport.

2022-10-15 19:34 UTC, oschulz commented on src/combinators/transformedmeasure.jl
> +    pushfwd(setinverse(f, inverse(f)), μ, volcorr)
This looks weird - if `f` has an inverse we shouldn't need to set it's inverse.

2022-10-15 19:48 UTC, cscherrer commented on src/combinators/transformedmeasure.jl
> +    pushfwd(setinverse(f, inverse(f)), μ, volcorr)
It's for uniformity. The main constructor is
```julia
function pushfwd(f::FunctionWithInverse, μ, volcorr::TransformVolCorr)
    PushforwardMeasure(f, inverse(f), μ, volcorr)
end
```

Other calls get passed to this, so we can assume `f` is always a `FunctionWithInverse`. 

Mostly it's nice to avoid having to worry about lots of special cases. In the last implementation of this, I had that `f` and `finv` were _never_ `FunctionWithInverse` - if it saw one of those it would pull it apart. If we don't want that, the best alternative I see is to _always_ have `FunctionWithInverse`. 

The only other possibility is to just let everything be arbitrary. In that case construction is easy, but any use of a `PushforwardMeasure` would need to have methods for the different cases. This seems very awkward to me. If you think it could be better, maybe a PR into `dev` and we can discuss?

2022-10-15 19:51 UTC, cscherrer commented on src/combinators/transformedmeasure.jl
> +    finv::I
That's very awkward to me. We talk about "inverse CDF" or "inverse sine / arcsin". But for functions with a generic name, we usually say "f" and "f inverse".

2022-10-15 19:52 UTC, cscherrer commented on src/combinators/transformedmeasure.jl
> +function transport_def(ν::PushforwardMeasure{F,I,M}, μ::M, x) where {F,I,M}
Good catch! I'll update this, let's wait to resolve this comment until I do.

2022-10-15 20:04 UTC, oschulz commented on src/combinators/transformedmeasure.jl
> +    finv::I
Sure, I don't have a strong opinion here.

2022-10-15 21:35 UTC, oschulz commented on src/standard/stdlogistic.jl
> +@inline transport_def(::StdUniform, μ::StdLogistic, x) = smf(StdLogistic(), x)
This indirection may cause a longer tape with Zygote

2022-10-15 21:50 UTC, oschulz commented on src/combinators/transformedmeasure.jl
> +function pushfwd(f, μ::PushforwardMeasure, ::WithVolCorr)
Is this necessary to resolve dispatch ambiguities?

2022-10-15 21:52 UTC, oschulz commented on src/combinators/transformedmeasure.jl
> +    pushfwd(f ∘ μ.f, μ.origin, v)
Maybe use `FunctionChains.fchain((μ.f, f))` here until Julia v1.9 is released, since chained `∘` is not type-stable in v1.8 (but is type stable in v1.6).

2022-10-15 23:03 UTC, merged